set(CPACK_PACKAGE_NAME "cpackexample")
set(CPACK_PACKAGE_VENDOR "B3tah3")
set(CPACK_PACKAGE_DESCRIPTION "My packaging of the exercise code with cpack")
set(CPACK_PACKAGE_HOMEPAGE_URL "https://github.com/B3tah3/cpack-exercise-wt2526")

set(CPACK_STRIP_FILES "TRUE")

set(CPACK_BINARY_DEB "ON")
set(CPACK_BINARY_TGZ "ON")
set(CPACK_BINARY_TZ "OFF")
set(CPACK_BINARY_STGZ "OFF")

set(CPACK_DEB_COMPONENT_INSTALL "ON")
set(CPACK_DEBIAN_PACKAGE_NAME "cpackexample")
set(CPACK_DEBIAN_FILE_NAME "DEB-DEFAULT")
set(CPACK_DEBIAN_PACKAGE_VERSION 1)
set(CPACK_DEBIAN_PACKAGE_ARCHITECTURE "amd64")
set(CPACK_DEBIAN_PACKAGE_MAINTAINER "B3tah3")
set(CPACK_DEBIAN_PACKAGE_SECTION "devel")
set(CPACK_DEBIAN_ARCHIVE_TYPE "gnutar")
set(CPACK_DEBIAN_COMPRESSION_TYPE "gzip")
set(CPACK_DEBIAN_PACKAGE_PRIORITY "optional")

include(CPack)